### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [hlynka-a/Unity3D_Mesh_Editing_Demo#1]
Hello, under what license is this project released under ? Thank-you.

**Comment by hlynka-a** [comment]
I just updated the README file on the project's page for "Unity3D_Mesh_Editing_Demo."
The project is **open-source** under the **Apache License 2.0** agreement. You can use/modify/redistribute this project for commercial/non-commercial purposes.

If you do use this or make something cool out of it (paid or not), I would love to hear about it. Feel free to leave a comment or post a new issue here for others to see it in the future.

Thanks for asking!
